version: '2'
services:
    deadlock:
        build: .
        volumes:
            - .:/usr/src/app
    db:
        image: mysql:5.7
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: deadlock
